apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  selector:
    matchLabels:
      app: server
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: server
        tier: frontend
    spec:
      containers:
        - name: master
          image: local/app
          imagePullPolicy: Never
          args:
            - app
          ports:
            - containerPort: 3232
              name: server
          env:
            - name: REDIS_ADDRESS
              value: "redis:6379"
          resources:
            limits:
              cpu: "0.1"